config/routes.rb
Sneakerbook::Application.routes.draw do
  root :to => redirect('/sneakers')
  get "pages/info"

  resources :comments

  resources :sneakers

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :sneaker
  attr_accessible :body, :sneaker_id, :user_name
end

app/models/sneaker.rb
class Sneaker < ActiveRecord::Base
  has_many :comments
  mount_uploader :picture, PictureUploader
  attr_accessible :description, :designer, :name, :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  # GET /sneakers
  # GET /sneakers.json
  def index
    @sneakers = Sneaker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sneakers }
    end
  end

  # GET /sneakers/1
  # GET /sneakers/1.json
  def show
    @sneaker = Sneaker.find(params[:id])
    @comments = @sneaker.comments.all
    @comment = @sneaker.comments.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sneaker }
    end
  end

  # GET /sneakers/new
  # GET /sneakers/new.json
  def new
    @sneaker = Sneaker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sneaker }
    end
  end

  # GET /sneakers/1/edit
  def edit
    @sneaker = Sneaker.find(params[:id])
  end

  # POST /sneakers
  # POST /sneakers.json
  def create
    @sneaker = Sneaker.new(params[:sneaker])

    respond_to do |format|
      if @sneaker.save
        format.html { redirect_to @sneaker, notice: 'Sneaker was successfully created.' }
        format.json { render json: @sneaker, status: :created, location: @sneaker }
      else
        format.html { render action: "new" }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sneakers/1
  # PUT /sneakers/1.json
  def update
    @sneaker = Sneaker.find(params[:id])

    respond_to do |format|
      if @sneaker.update_attributes(params[:sneaker])
        format.html { redirect_to @sneaker, notice: 'Sneaker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sneakers/1
  # DELETE /sneakers/1.json
  def destroy
    @sneaker = Sneaker.find(params[:id])
    @sneaker.destroy

    respond_to do |format|
      format.html { redirect_to sneakers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sneakers_helper.rb
module SneakersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
    <%= f.hidden_field :sneaker_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <tr>
    <th>User name</th>
    <th>Body</th>
    <th>Sneaker</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user_name %></td>
    <td><%= comment.body %></td>
    <td><%= comment.sneaker_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User name:</b>
  <%= @comment.user_name %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Sneaker:</b>
  <%= @comment.sneaker_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sneakerbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Sneakerbook</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/sneakers">Sneakers</a></li>
        <li ><%= link_to 'New Sneaker', new_sneaker_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    Antonia Blair 2014
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>

app/views/pages/info.html.erb
<h1>About Us</h1>
# Find me in app/views/pages/info.html.erb
<br>
<p>We are a dedicated team of sneaker enthusiasts. 

app/views/sneakers/_form.html.erb
<%= form_for(@sneaker) do |f| %>
  <% if @sneaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sneaker.errors.count, "error") %> prohibited this sneaker from being saved:</h2>

      <ul>
      <% @sneaker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :designer %><br />
    <%= f.text_field :designer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sneakers/edit.html.erb
<h1>Editing sneaker</h1>

<%= render 'form' %>

<%= link_to 'Show', @sneaker %> |
<%= link_to 'Back', sneakers_path %>

app/views/sneakers/index.html.erb
<h1>Sneakerbook</h1>

<table class="container">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Picture</th>
    <th>Designer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sneakers.each do |sneaker| %>
  <tr>
    <td><%= sneaker.name %></td>
    <td><%= sneaker.description %></td>
    <td><img style="width: 50px;" src="<%= sneaker.picture %>" /></td>
    <td><%= sneaker.designer %></td>
    <td><%= link_to 'Show', sneaker %></td>
    <td><%= link_to 'Edit', edit_sneaker_path(sneaker) %></td>
    <td><%= link_to 'Destroy', sneaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sneaker', new_sneaker_path %>

app/views/sneakers/new.html.erb
<h1>New sneaker</h1>

<%= render 'form' %>

<%= link_to 'Back', sneakers_path %>

app/views/sneakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sneaker.name %>
</p>

<p>
  <b>Description:</b>
  <%= @sneaker.description %>
</p>

<p>
  <b>Picture:</b>
  <%= image_tag(@sneaker.picture_url, :width => 300) if @sneaker.picture.present? %>
  <h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br />
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>
<%= render 'comments/form' %>
</p>

<p>
  <b>Designer:</b>
  <%= @sneaker.designer %>
</p>


<%= link_to 'Edit', edit_sneaker_path(@sneaker) %> |
<%= link_to 'Back', sneakers_path %>